security:
    enable_authenticator_manager: true
    firewalls:
        default:
            custom_authenticators:
                - EcPhp\CasBundle\Security\CasAuthenticator

    access_control:
        - { path: ^/api, role: ROLE_CAS_AUTHENTICATED }