cas:
  base_url: https://localhost:8443/cas
  protocol:
    login:
      path: /login
    serviceValidate:
      default_parameters:
        format: JSON
        pgtUrl: cas_bundle_proxy_callback
      path: /p3/serviceValidate
    logout:
      default_parameters:
        service: homepage
      path: /logout
    proxy:
      path: /proxy
    proxyValidate:
      path: /p3/proxyValidate
      default_parameters:
        format: JSON
        pgtUrl: cas_bundle_proxy_callback
