cas:
  base_url: https://ecas.ec.europa.eu/cas/
  protocol:
    login:
      path: /login
    serviceValidate:
      path: /serviceValidate
      default_parameters:
        userDetails: "true"
        format: XML
        groups: "*"
        #pgtUrl: cas_bundle_proxy_callback
    logout:
      path: /logout
      default_parameters:
        service: homepage
    proxy:
      path: /proxy
    proxyValidate:
      path: /proxyValidate
      default_parameters:
        userDetails: "true"
        format: XML
        #pgtUrl: cas_bundle_proxy_callback
