services:
  eulogin.userprovider:
    class: EcPhp\EuLoginBundle\Security\Core\User\EuLoginUserProvider
  cas:
    class: EcPhp\Ecas\Ecas
    arguments:
      $serverRequest: '@cas.psrrequest'
      $properties: '@ConfigurableSymfony'
      $client: '@psr18.http_client'
      $uriFactory: '@nyholm.psr7.psr17_factory'
      $responseFactory: '@nyholm.psr7.psr17_factory'
      $requestFactory: '@nyholm.psr7.psr17_factory'
      $streamFactory: '@nyholm.psr7.psr17_factory'
      $cache: '@cache.app'
      $logger: '@logger'